require('../script/array_detect');
require('../script/game/fixed-game-loop');
require('../script/game/scheduler');
require('../script/game/screen');
require('../script/asteroids/main');
require('../script/asteroids/draw');
require('../script/asteroids/update');
require('../script/game/assets');
exports.Experiment = Experiment;
exports.Game = Game;
